name: conin
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - glpk
  - munch
  - numpy
  - pandas
  - pip
  - pip:
    - pytoulbar2
  - pyomo
